// This file is generated by srpc-derive

import { rpcCall } from './rpcClient';

export const client = {
    get_first_user: async () => rpcCall('get_first_user'),
    get_second_user: async () => rpcCall('get_second_user'),
};
