// This file is generated by srpc-derive

import { rpcCall } from './rpcClient';

export const client = {
    user_list: async () => rpcCall('user_list'),
    get_first_user: async () => rpcCall('get_first_user'),
    foobar: async () => rpcCall('foobar'),
};