// This file is generated by srpc-derive

import { rpcCall } from './rpcClient';
import { z } from 'zod';

export const userListSchema = z.array(
    z.object({
        id: z.number(),
        name: z.string(),
    })
);

export const getFirstUserSchema = z.object({
    id: z.number(),
    name: z.string(),
});

export const foobarSchema = z.number();

export const client = {
    userList: async () => rpcCall('user_list', userListSchema),
    getFirstUser: async () => rpcCall('get_first_user', getFirstUserSchema),
    foobar: async () => rpcCall('foobar', foobarSchema),
};
